# Generated by Django 2.0 on 2018-02-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_today', models.BigIntegerField(blank=True, null=True)),
                ('total_overall', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counters',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Record_Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_today', models.BigIntegerField(blank=True, null=True)),
                ('total_overall', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Record_Visitors',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Visitors',
                'ordering': ['ip'],
            },
        ),
        migrations.AddField(
            model_name='record_visitor',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Visitor'),
        ),
    ]
